version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lemphis
  redis:
    container_name: redis
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"